//! `SeaORM` Entity, @generated by sea-orm-codegen 1.0.0

pub use super::organizations::Entity as Organizations;
pub use super::prompts::Entity as Prompts;
pub use super::user_organizations::Entity as UserOrganizations;
pub use super::users::Entity as Users;
